POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI4NDAxODYwLCJ1c2VySWQiOjJ9.MfgJDPZ0yefAybYt8b8_w2RXtb64lghoZn36zgxcL90


{
    "name":"panda Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}