PUT http://localhost:8080/events/2
Content-Type: application/json


{
  "Name": "Updated Test event",
  "Description": "A test event",
  "Location": "A test location",
  "DateTime": "2025-01-01T15:30:00Z"
}